.travis.yml, cove_ocds/locale/en/LC_MESSAGES/django.po, cove_ocds/locale/es/LC_MESSAGES/django.po
https://github.com/open-contracting/cove-ocds/pull/7
Work by @rhiaro, rebased and squashed by James
=> Add travis checks for translations

requirements.txt, requirements_dev.txt
This updates lib-cove to the latest release, so fixes
https://github.com/OpenDataServices/cove/issues/1237
=> requirements: Update all requirements

docs/architecture.rst, docs/how-to-add-a-validation-check.rst
Document Additional Checks in more detail to make it easier for people to add new checks.
[Preview](https://ocds-data-review-tool.readthedocs.io/en/docs-howto/how-to-add-a-validation-check.html)
=> docs: Outline for adding checks

cove_ocds/tests_functional.py
description/en in this file has changed:
https://raw.githubusercontent.com/open-contracting/ocds_lots_extension/master/extension.json
=> tests: Update lots extension description test to match latest json

.travis.yml, cove_ocds/fixtures/30_records.json, cove_ocds/fixtures/30_releases.json, cove_ocds/fixtures/7_records.json, cove_ocds/locale/en/LC_MESSAGES/django.po, cove_ocds/locale/es/LC_MESSAGES/django.po, cove_ocds/templates/cove_ocds/explore_record.html, cove_ocds/templates/cove_ocds/explore_release.html, cove_ocds/tests_functional.py, cove_project/context_processors.py, cove_project/settings.py, docs/how-to-config-frontend.rst, docs/index.rst, requirements.txt, requirements_dev.txt
=> Make number of rows in Releases and Records Table configureable

cove_project/templates/terms_conditions_intro.html, cove_project/templates/terms_privacy_intro.html, cove_project/templates/terms_tracker_data_controller_international.html, cove_project/templates/terms_tracker_no_international.html, requirements.in, requirements.txt, requirements_dev.txt
From https://github.com/OpenDataServices/lib-cove-web/pull/52
=> terms: Move OCDS specific terms text into this repo

.travis.yml, cove_ocds/tests.py, cove_ocds/views.py, requirements.in, requirements.txt, requirements_dev.txt
Removed from lib-cove in https://github.com/OpenDataServices/lib-cove/pull/55
=> refactor: Distinguish between releases and records here, not in lib-cove 

.tx/config
https://www.transifex.com/open-contracting-partnership-1/cove-1/dashboard/
I've pushed the strings and their translations up to this.
=> transifex: Switch to a new project under the OCP organisation

requirements.in, requirements.txt, requirements_dev.txt
(because the package is now fixed https://github.com/OpenDataServices/lib-cove-web/pull/39)
=> requirements: Install libcoveweb from PyPI

.github/workflows/ci.yml
https://github.com/open-contracting/cove-ocds/issues/30
=> github: Add coverage command to GitHub actions

requirements.in, requirements.txt, requirements_dev.txt
https://github.com/OpenDataServices/cove/issues/1285
=> requirements: latest flatten-tool, with sheet names in more warnings

cove_ocds/tests_functional.py
https://github.com/open-contracting/cove-ocds/issues/59
=> tests: Fix live tests by skipping those that require env vars to be set

cove_ocds/templates/cove_ocds/explore_record.html, cove_ocds/tests_functional.py
https://github.com/open-contracting/cove-ocds/issues/80
=> explore_record: Fix release count in records table

cove_ocds/templates/cove_ocds/explore_base.html
https://github.com/open-contracting/cove-ocds/issues/81
=> templates: Rename codelist panels, stop conflict with additional fields

cove_ocds/tests_functional.py
https://github.com/open-contracting/cove-ocds/issues/59
=> tests: Skip all tests on remote sites that could be affected by env vars

cove_ocds/templates/cove_ocds/explore_record.html, cove_ocds/templates/cove_ocds/validation_table.html, cove_ocds/views.py, requirements.txt, requirements_dev.txt
This will add all the Spanish translations that were done for cove-oc4ids (e.g. the most common validation error messages).
=> Update requirements, and makes fixes for new libcove/libcoveweb

.github/workflows/ci.yml, requirements.txt
https://github.com/OpenDataServices/lib-cove-web/issues/66
=> requirements: Update lib-cove-web to avoid `NameError`

requirements.txt, requirements_dev.txt
Creating PR from old branch by @Bjwebb
=> requirements: Update reqs, including latest flattentool and libcove

requirements.txt, requirements_dev.txt
Potential directory-traversal via uploaded files:
https://docs.djangoproject.com/en/3.2/releases/3.2.1/
=> requirements: Update Django for security update

cove_ocds/views.py, requirements.txt, requirements_dev.txt, tests/test_general.py
https://github.com/OpenDataServices/lib-cove-web/issues/74
=> Links to codelists - rewrite to OCDS Standard. & Upgrade lib-cove-web
